### ISSUE TITLE
node-mpg123-util broken on newer node versions

### ISSUE THREAD

**Issue by bid** [G33kLabs/node-tts-speak#3]
node-mpg123-util doesn't build on newer node versions, effectively breaking this package too.

More info here: https://github.com/jkeylu/node-mpg123-util/issues/2

**Comment by jkeylu** [comment]
@bid fixed on node-mpg123-util v0.0.2

**Comment by jsonfry** [comment]
Can you push the change made for this to npm? Cheers.

**Comment by G33kLabs** [comment]
Done : v1.1.1 !

**Comment by jsonfry** [comment]
Wow! That was quick, thank you.
